spring:
  datasource:
    username:
    password:
    driver-class-name:
    url:
  jpa:
    hibernate:
      ddl-auto:
  grpc:
    server:
      host:
      port:
kafka:
  group-id:
  topic:
    merchant-details:
      receive: